FROM nikolaik/python-nodejs:python3.8-nodejs14-alpine

WORKDIR /usr/home

RUN pip install connexion[swagger-ui]

RUN pip install pyyaml

RUN npm install -g swagger-cli

COPY ./api .

RUN swagger-cli bundle oarApi.yaml --outfile _build/oarApi.yaml --type yaml

EXPOSE 8080

CMD python ./oarApi.py
# CMD connexion run ./_build/oarApi.yaml --mock=all -v