version: '3.4'

services:
  oar.apps.webspa:
    image: oar.apps.webspa
    build:
      context: ./oar.apps.webspa
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 80
      - 8080:80
    tty: true
