FROM nikolaik/python-nodejs:python3.8-nodejs14-alpine

WORKDIR /usr/home

RUN pip install connexion[swagger-ui]

RUN pip install pyyaml

RUN npm install -g swagger-cli

COPY . .

RUN swagger-cli bundle app.yaml --outfile _build/app.yaml --type yaml

EXPOSE 8080

CMD python ./app.py
# CMD connexion run ./_build/app.yaml --mock=all -v