version: '3.4'

services:
  oar.apigateways.web.swagger.editor:
    image: oar.apigateways.web.swagger.editor
    build:
      context: .
      dockerfile: Dockerfile.swagger-editor
    environment:
      NODE_ENV: development
    ports:
      - 8080
      - ${APIGATEWAYS_WEB_SWAGGER_EDITOR_PORT}:8080
    tty: true
  oar.apigateways.web.mockserver:
    image: oar.apigateways.web.mockserver
    build:
      context: .
      dockerfile: Dockerfile.connexion
    environment:
      NODE_ENV: development
    ports:
      - 8080
      - ${APIGATEWAYS_WEB_MOCK_SERVER_PORT}:8080
    tty: true
